/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sisaudcom.crud.javaswing.view;

/**
 *
 * @author neros
 */
import javax.swing.JFrame;
import com.sisaudcom.crud.javaswing.model.Funcionario;
import com.sisaudcom.crud.javaswing.service.FuncionarioService;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    private void carregarFuncionarios() {

        FuncionarioService funcionarioService = new FuncionarioService();

        try {

            List<Funcionario> funcionarios
                    = funcionarioService.listarTodos();

            DefaultTableModel modelo
                    = (DefaultTableModel) funcionariosTable.getModel();

            modelo.setRowCount(0);

            SimpleDateFormat formato
                    = new SimpleDateFormat("dd/MM/yyyy");

            for (Funcionario funcionario : funcionarios) {

                modelo.addRow(new Object[]{
                    funcionario.getId(),
                    funcionario.getNome(),
                    formato.format(
                    funcionario.getDataDeAdmissao()
                    ),
                    funcionario.getSalario(),
                    funcionario.isStatus()
                    ? "Ativo"
                    : "Inativo"
                });
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar funcionários.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        URL caminhoIcone = getClass().getResource("/images/logo.png");

        if (caminhoIcone != null) {
            Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
            this.setIconImage(iconeTitulo);
        } else {
            System.err.println("Erro: O arquivo de imagem não foi encontrado no caminho especificado.");
        }

        setLocationRelativeTo(
                null);
        this.setExtendedState(JFrame.NORMAL);

        carregarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        funcionarioScrollPane = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionariosTable = new javax.swing.JTable();
        funcionarioPanel = new java.awt.Panel();
        cadastroButton = new javax.swing.JButton();
        statusCheckBox = new javax.swing.JCheckBox();
        salarioLabel = new javax.swing.JLabel();
        salarioTextField = new javax.swing.JTextField();
        dataDeAdmissaoLabel = new javax.swing.JLabel();
        dataAdmissaoFormattedTextField = new javax.swing.JFormattedTextField();
        nomeTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        sairLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(51, 51, 255));
        setResizable(false);

        funcionariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "DATA DE ADMISSÃO", "SALARIO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(funcionariosTable);

        funcionarioScrollPane.setViewportView(jScrollPane1);

        funcionarioPanel.setForeground(new java.awt.Color(204, 204, 204));

        cadastroButton.setText("Cadastrar");
        cadastroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroButton.addActionListener(this::cadastroButtonActionPerformed);

        statusCheckBox.setText("Ativo");

        salarioLabel.setText("Salário");

        dataDeAdmissaoLabel.setText("Data de Admissão");

        try {
            dataAdmissaoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        nomeLabel.setText("Nome");

        sairLabel.setText("<html><u>Sair</u></html>");
        sairLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairLabelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CADASTRAR NOVO FUNCIONARIO");

        javax.swing.GroupLayout funcionarioPanelLayout = new javax.swing.GroupLayout(funcionarioPanel);
        funcionarioPanel.setLayout(funcionarioPanelLayout);
        funcionarioPanelLayout.setHorizontalGroup(
            funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcionarioPanelLayout.createSequentialGroup()
                .addGroup(funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(salarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(cadastroButton))
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(nomeLabel))
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(dataDeAdmissaoLabel))
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(dataAdmissaoFormattedTextField))
                                .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(sairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(funcionarioPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(salarioLabel))))
                    .addGroup(funcionarioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusCheckBox))
                    .addGroup(funcionarioPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        funcionarioPanelLayout.setVerticalGroup(
            funcionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funcionarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataDeAdmissaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataAdmissaoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusCheckBox)
                .addGap(18, 18, 18)
                .addComponent(cadastroButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(funcionarioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funcionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(funcionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(funcionarioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairLabelMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
            dispose();
        });
    }//GEN-LAST:event_sairLabelMouseClicked

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed

        String nome = nomeTextField.getText().trim();
        String dataTexto = dataAdmissaoFormattedTextField.getText().trim();
        String salarioTexto = salarioTextField.getText().trim();

        if (nome.isBlank()
            || dataTexto.isBlank()
            || salarioTexto.isBlank()) {

            JOptionPane.showMessageDialog(
                this,
                "Preencha todos os campos.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            SimpleDateFormat formato
            = new SimpleDateFormat("dd/MM/yyyy");

            formato.setLenient(false);

            java.util.Date dataAdmissao
            = formato.parse(dataTexto);

            double salario
            = Double.parseDouble(
                salarioTexto.replace(",", ".")
            );

            Funcionario funcionario = new Funcionario();

            funcionario.setNome(nome);
            funcionario.setDataDeAdmissao(dataAdmissao);
            funcionario.setSalario(salario);
            funcionario.setStatus(
                statusCheckBox.isSelected()
            );

            FuncionarioService funcionarioService
            = new FuncionarioService();

            funcionarioService.cadastrar(funcionario);

            JOptionPane.showMessageDialog(
                this,
                "Funcionário cadastrado com sucesso!"
            );

            nomeTextField.setText("");
            dataAdmissaoFormattedTextField.setText("");
            salarioTextField.setText("");
            statusCheckBox.setSelected(false);

            carregarFuncionarios();

        } catch (ParseException e) {

            JOptionPane.showMessageDialog(
                this,
                "Informe uma data válida no formato dd/MM/yyyy.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "Informe um salário válido.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                this,
                "Erro ao cadastrar funcionário no banco de dados.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_cadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JFormattedTextField dataAdmissaoFormattedTextField;
    private javax.swing.JLabel dataDeAdmissaoLabel;
    private java.awt.Panel funcionarioPanel;
    private javax.swing.JScrollPane funcionarioScrollPane;
    private javax.swing.JTable funcionariosTable;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel sairLabel;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JTextField salarioTextField;
    private javax.swing.JCheckBox statusCheckBox;
    // End of variables declaration//GEN-END:variables
}
